remove question mark from ipynb filename
The "?" in the filename cause the following error when git cloning the repo:

error: unable to create file Capsule Networks What Comes after Convolutional Networks?.ipynb: Invalid argument
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.